#开发环境
#debug: true
server:
  port: 8080
spring:
  redis:
    database: 0
    host: 192.168.115.131 #redis安装在虚拟机上，此处为虚拟机ip地址
    port: 6379
    password: zhangyanping
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    timeout: 10000  #redis 连接超时时间ms
  #  jackson:
  #    date-format: yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT+8
  #  cache:
  #    type: redis
  #    redis:
  #      time-to-live: 20000 #缓存超时时间ms
  #      cache-null-values: false #是否缓存空值
  #Redis Configuration